[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sports"
version = "0.1.0"
description = "Tools and demos for sports-focused computer vision."
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name = "Piotr Skalski", email = "piotr.skalski92@gmail.com"}
]
dependencies = [
  "supervision",
  "numpy",
  "ultralytics>=8.3.237",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: MacOS"
]

[project.optional-dependencies]
tests = [
  "pytest"
]

[project.urls]
homepage = "https://github.com/roboflow/sports"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["sports*"]
